LATEX_FILENAME	= cs472_HW3_bridgewd_philliry
FLAGS  		=
LIBS   		=

default: latex

latex: $(LATEX_FILENAME).tex
	pdflatex $(LATEX_FILENAME).tex

clean:
	rm $(TARGET) *_results $(LATEX_FILENAME).aux $(LATEX_FILENAME).log \
		$(LATEX_FILENAME).out $(LATEX_FILENAME).toc \
		$(LATEX_FILENAME).synctex.gz $(LATEX_FILENAME).pdf
